{
	"version": 1615687700,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/9patch.png",
		"images/anjanifix-sheet0.png",
		"images/anjanifix-sheet1.png",
		"images/bawah2-sheet0.png",
		"images/background-sheet0.png",
		"images/bintang-sheet0.png",
		"images/hati-sheet0.png",
		"images/jam-sheet0.png",
		"images/kartunbenar2-sheet0.png",
		"images/papanbarfix-sheet0.png",
		"images/papanjawaban-sheet0.png",
		"images/papanmenugame-sheet0.png",
		"images/papansoal-sheet0.png",
		"images/tiledbackground.png",
		"images/nomor.png",
		"images/papannomor-sheet0.png",
		"images/papanpertanyaan-sheet0.png",
		"images/spritefont2.png",
		"images/spritefont3.png",
		"images/tiledbackground2.png",
		"images/tombol_akhir_game-sheet0.png",
		"images/tombol_akhir_game-sheet1.png",
		"images/tombol_akhir_game-sheet2.png",
		"images/wayanggunung-sheet0.png",
		"images/pause2-sheet0.png",
		"images/bermain-sheet0.png",
		"images/bermain-sheet1.png",
		"images/layer2-sheet0.png",
		"images/layer2-sheet1.png",
		"images/mainmenu-sheet0.png",
		"images/pengembang2-sheet0.png",
		"images/peringatan2-sheet0.png",
		"images/tebakwayang-sheet0.png",
		"images/anjanidongeng-sheet0.png",
		"images/anjani-sheet0.png",
		"images/background2-sheet0.png",
		"images/buttonkanan-sheet0.png",
		"images/buttonkanan-sheet1.png",
		"images/kisahanjani-sheet0.png",
		"images/kisahanjani-sheet1.png",
		"images/papan-sheet0.png",
		"images/anjani2-sheet0.png",
		"images/subjeksoal-sheet0.png",
		"images/soal-sheet0.png",
		"images/bar.png",
		"images/back.png",
		"images/dalang2-sheet0.png",
		"media/bgm.ogg",
		"media/click_1.ogg",
		"media/sound-benar.ogg",
		"media/sound-menangt_1.ogg",
		"media/suara salah new.ogg",
		"media/bintang 1.ogg",
		"media/bintang 2.ogg",
		"media/bintang 3.ogg",
		"media/suara kalah.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}